### ISSUE TITLE
PingMessage should be marked as immutable 

### ISSUE THREAD

**Issue by oising** [bt-skyrise/actor-benchmark#1]
https://github.com/bt-skyrise/actor-benchmark/blob/6fbdbe10b3e1d57e0c7e73f0b351d9901e5615ff/OrleansSut.Shared/IPingPongGrain.cs#L10

By not using an immutable message with either `readonly record struct` (for messages 16 bytes or under, optimally) or the attribute `[Immutable] ` on record classes (for larger messages), this benchmark will incur additional serialization round tripping overhead.

**Comment by marcinbudny** [comment]
Changes merged and results posted in #2.
