### ISSUE TITLE
Grain interface methods should return ValueTask

### ISSUE THREAD

**Issue by oising** [bt-skyrise/actor-benchmark#2]
https://github.com/bt-skyrise/actor-benchmark/blob/6fbdbe10b3e1d57e0c7e73f0b351d9901e5615ff/OrleansSut.Shared/IPingPongGrain.cs#L7

Prefer ValueTask<T> for grain interface methods to avoid the GC allocation. Grains are inherently single threaded by design, so using Task<T> is almost certainly unnecessary.

**Comment by marcinbudny** [comment]
Thank you for pointing out the possible optimizations.

I reran the Orleans messaging benchmark before and after applying #3  - to include changes from this issue and #2. 

```
Clients: 750
Before:  335 448 req/s
After: 358 059 req/s
```
Which is ~6,7% improvement 👍
